// Code generated by MockGen. DO NOT EDIT.
// Source: ai.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	ai "github.com/Y1le/agri-price-crawler/internal/ai"
	gomock "github.com/golang/mock/gomock"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// RecipeGenerator mocks base method.
func (m *MockFactory) RecipeGenerator() ai.RecipeFactory {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecipeGenerator")
	ret0, _ := ret[0].(ai.RecipeFactory)
	return ret0
}

// RecipeGenerator indicates an expected call of RecipeGenerator.
func (mr *MockFactoryMockRecorder) RecipeGenerator() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecipeGenerator", reflect.TypeOf((*MockFactory)(nil).RecipeGenerator))
}
