// Code generated by MockGen. DO NOT EDIT.
// Source: internal/craw/mailer/mailer.go

// Package mailer is a generated GoMock package.
package mailer

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMailer is a mock of Mailer interface.
type MockMailer struct {
	ctrl     *gomock.Controller
	recorder *MockMailerMockRecorder
}

// MockMailerMockRecorder is the mock recorder for MockMailer.
type MockMailerMockRecorder struct {
	mock *MockMailer
}

// NewMockMailer creates a new mock instance.
func NewMockMailer(ctrl *gomock.Controller) *MockMailer {
	mock := &MockMailer{ctrl: ctrl}
	mock.recorder = &MockMailerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailer) EXPECT() *MockMailerMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockMailer) Send(email Email) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockMailerMockRecorder) Send(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMailer)(nil).Send), email)
}

// SendBulkEmails mocks base method.
func (m *MockMailer) SendBulkEmails(recipients []Recipient, subject, htmlBody string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBulkEmails", recipients, subject, htmlBody)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendBulkEmails indicates an expected call of SendBulkEmails.
func (mr *MockMailerMockRecorder) SendBulkEmails(recipients, subject, htmlBody interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBulkEmails", reflect.TypeOf((*MockMailer)(nil).SendBulkEmails), recipients, subject, htmlBody)
}
